<?php

$title = 'Delete episode';
$url = $this->url('admin/episode', ['action' => 'delete', 'id' => $id, 'id_season' => $id_season]);

$this->headTitle($title);
?>

<div class="content-admin">
    <p>
        <a href="<?= $this->url('admin/episode', ['action' => 'index', 'id_season' => $id_season])?>"><i class="fas fa-arrow-left"></i> Voltar Lista Episódios</a>
    </p>
    <h1><?= $this->escapeHtml($title) ?></h1>
    <p>
        Are you sure that you want to delete
        "<?= $this->escapeHtml('Episódio ' . $episode->episode) ?>" ?
    </p>

    <form action="<?= $url ?>" method="post">
        <div class="form-group">
            <input type="hidden" name="id" value="<?= (int) $episode->id_episode ?>" />
            <input type="submit" class="btn btn-danger" name="del" value="Yes" />
            <input type="submit" class="btn btn-success" name="del" value="No" />
        </div>
    </form>
</div>