<?php

$title = 'Add new anime';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
// This provides a default CSS class and placeholder text for the title element:
$anime = $form->get('title');
$anime->setAttribute('class', 'form-control');
$anime->setAttribute('placeholder', 'Anime title');

// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('anime', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
?>

<?php // Wrap the elements in divs marked as form groups, and render the
      // label, element, and errors separately within ?>
<div class="form-group">
    <?= $this->formLabel($anime) ?>
    <?= $this->formElement($anime) ?>
    <?= $this->formElementErrors()->render($anime, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();