<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('anime', ['action' => 'add']) ?>">Add new anime</a>
</p>

<table class="table">
<tr>
    <th>Title</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($animes as $anime) : ?>
    <tr>
        <td><?= $this->escapeHtml($anime->title) ?></td>
        <td>
            <a href="<?= $this->url('anime', ['action' => 'edit', 'id' => $anime->id]) ?>">Edit</a>
            <a href="<?= $this->url('anime', ['action' => 'delete', 'id' => $anime->id]) ?>">Delete</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>
<script>

   $(document).ready(function(){
    
   })

</script>