<?php

$title = 'Delete season';
$url = $this->url('admin/season', ['action' => 'delete', 'id' => $id, 'id_anime' => $id_anime]);

$this->headTitle($title);
?>

<div class="content-admin">
    <p>
        <a href="<?= $this->url('admin/season', ['action' => 'index', 'id_anime' => $id_anime])?>"><i class="fas fa-arrow-left"></i> Voltar Lista Temporadas</a>
    </p>
    <h1><?= $this->escapeHtml($title) ?></h1>
    <p>
        Are you sure that you want to delete
        "<?= $this->escapeHtml('Temporada ' . $season->season) ?>" ?
    </p>

    <form action="<?= $url ?>" method="post">
        <div class="form-group">
            <input type="hidden" name="id" value="<?= (int) $season->id_season ?>" />
            <input type="submit" class="btn btn-danger" name="del" value="Yes" />
            <input type="submit" class="btn btn-success" name="del" value="No" />
        </div>
    </form>
</div>