<?php

$title = 'Delete video';
$url = $this->url('admin/video', ['action' => 'delete', 'id' => $id, 'id_episode' => $id_episode]);

$this->headTitle($title);
?>

<div class="content-admin">
    <p>
        <a href="<?= $this->url('admin/video', ['action' => 'index', 'id_episode' => $id_episode])?>"><i class="fas fa-arrow-left"></i> Voltar lista videos</a>
    </p>
    <h1><?= $this->escapeHtml($title) ?></h1>
    <p>
        Are you sure that you want to delete
        "<?= $this->escapeHtml('Video ' . $video->server) ?>" ?
    </p>

    <form action="<?= $url ?>" method="post">
        <div class="form-group">
            <input type="hidden" name="id" value="<?= (int) $video->id_video ?>" />
            <input type="submit" class="btn btn-danger" name="del" value="Yes" />
            <input type="submit" class="btn btn-success" name="del" value="No" />
        </div>
    </form>
</div>