<?php

$title = 'Add new anime';
$this->headTitle($title);
?>
<div class="content-admin">
    <p>
        <a href="<?= $this->url('admin/anime', ['action' => 'index']) ?>"><i class="fas fa-arrow-left"></i> Voltar index</a>
    </p>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
// This provides a default CSS class and placeholder text for the title element:
$title = $form->get('title');
$title->setAttribute('class', 'form-control');
$title->setAttribute('placeholder', 'Title');

$route = $form->get('route');
$route->setAttribute('class', 'form-control');
$route->setAttribute('placeholder', 'Route');

$name = $form->get('name');
$name->setAttribute('class', 'form-control');
$name->setAttribute('placeholder', 'Name');

$description = $form->get('description');
$description->setAttribute('class', 'form-control');
$description->setAttribute('placeholder', 'Description');
$description->setAttribute('maxlength', '285');

$year = $form->get('year');
$year->setAttribute('class', 'form-control');
$year->setAttribute('placeholder', 'Year');

$episodes = $form->get('episodes');
$episodes->setAttribute('class', 'form-control');
$episodes->setAttribute('placeholder', 'Episodes');

$seasons = $form->get('seasons');
$seasons->setAttribute('class', 'form-control');
$seasons->setAttribute('placeholder', 'Seasons');

$status = $form->get('status');
$status->setAttribute('class', 'form-control');
$status->setAttribute('placeholder', 'Status');

$genre = $form->get('genre');
$genre->setAttribute('class', 'form-control');
$genre->setAttribute('placeholder', 'Status');

$image = $form->get('image');
$image->setAttribute('class', 'form-control');
$image->setAttribute('placeholder', 'Image');
$image->setAttribute('data-toggle', 'tooltip');
$image->setAttribute('title', 'Thumbnail anime');

$video = $form->get('video');
$video->setAttribute('class', 'form-control');
$video->setAttribute('placeholder', 'Video');
$video->setAttribute('data-toggle', 'tooltip');
$video->setAttribute('title', 'Trailer anime');

$category = $form->get('category');
$category->setAttribute('class', 'form-control');
$category->setAttribute('placeholder', 'Category');

$author = $form->get('author');
$author->setAttribute('class', 'form-control');
$author->setAttribute('placeholder', 'Author');

// This provides

// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('admin/anime', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
?>

<?php // Wrap the elements in divs marked as form groups, and render the
// label, element, and errors separately within ?>
    <div class="form-group">

        <?= $this->formElement($title) ?>
        <?= $this->formElementErrors()->render($title, ['class' => 'help-block']) ?>

        <?= $this->formElement($route) ?>
        <?= $this->formElementErrors()->render($route, ['class' => 'help-block']) ?>

        <?= $this->formElement($name) ?>
        <?= $this->formElementErrors()->render($name, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">

        <?= $this->formElement($year) ?>
        <?= $this->formElementErrors()->render($year, ['class' => 'help-block']) ?>

        <?= $this->formElement($episodes) ?>
        <?= $this->formElementErrors()->render($episodes, ['class' => 'help-block']) ?>

        <?= $this->formElement($seasons) ?>
        <?= $this->formElementErrors()->render($seasons, ['class' => 'help-block']) ?>

        <?= $this->formElement($status) ?>
        <?= $this->formElementErrors()->render($status, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">

        <?= $this->formElement($description) ?>
        <?= $this->formElementErrors()->render($description, ['class' => 'help-block']) ?>

        <?= $this->formElement($image) ?>
        <?= $this->formElementErrors()->render($image, ['class' => 'help-block']) ?>

        <?= $this->formElement($video) ?>
        <?= $this->formElementErrors()->render($video, ['class' => 'help-block']) ?>

    </div>

    <div class="form-group">
        <?= $this->formElement($category) ?>
        <?= $this->formElementErrors()->render($category, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formElement($author) ?>
        <?= $this->formElementErrors()->render($author, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formElement($genre) ?>
        <?= $this->formElementErrors()->render($genre, ['class' => 'help-block']) ?>
    </div>


<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id_anime'));
echo $this->form()->closeTag(); ?>
</div>

<script>
    $(document).ready(function(){
        $('#select-category').select2({
            tags: true,
            createTag: function (params) {
                return {
                    id: params.term,
                    text: params.term,
                    newOption: true
                }
            }
        });

        $('#select-author').select2({
            tags: true,
            createTag: function (params) {
                return {
                    id: params.term,
                    text: params.term,
                    newOption: true
                }
            }
        });

        $('#select-genre').select2({
            tags: true,
            createTag: function (params) {
                return {
                    id: params.term,
                    text: params.term,
                    newOption: true
                }
            }
        });
    });
</script>
