<?php

$title = 'Delete anime';
$url   = $this->url('admin/anime', ['action' => 'delete', 'id' => $id]);

$this->headTitle($title);
?>

<div class="content-admin">
    <p>
        <a href="<?= $this->url('admin/anime', ['action' => 'index']) ?>"><i class="fas fa-arrow-left"></i> Voltar index</a>
    </p>
    <h1><?= $this->escapeHtml($title) ?></h1>
    <p>
    Are you sure that you want to delete
    "<?= $this->escapeHtml($anime->title) ?>" ?
    </p>

    <form action="<?= $url ?>" method="post">
    <div class="form-group">
        <input type="hidden" name="id" value="<?= (int) $anime->id_anime ?>" />
        <input type="submit" class="btn btn-danger" name="del" value="Yes" />
        <input type="submit" class="btn btn-success" name="del" value="No" />
    </div>
    </form>
</div>