<?= $this->doctype() ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Animesflix')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/Anime/icons/logo.png'])
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/admin.css'))
        ->prependStylesheet($this->basePath('css/select2.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ->prependStylesheet($this->basePath('css/fontawesome-free-5.5.0-web/css/all.min.css'))
        ->prependStylesheet('https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css')
    ?>

    <!-- Scripts -->
    <?= $this->headScript()
        ->prependFile('https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js')
        ->prependFile($this->basePath('js/module/Application/Player/Player.js'))
        ->prependFile($this->basePath('js/module/Application/Index/App.js'))
        ->prependFile($this->basePath('js/select2.min.js'))
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery-ui.min.js'))
        ->prependFile($this->basePath('js/jquery-3.3.1.min.js'))

    ?>

</head>
<body>
<div class="content">
    <?= $this->content ?>
</div>
<?= $this->inlineScript() ?>
</body>
</html>
