<div id="wrapper">
    <h3>Continuar Assistindo</h3>

    <div class="slider-items clearfix">
        <ul>
            <?php foreach ($animes as $anime) : ?>
                <li class="slider-card">
                    <a href="<?= $anime->route ?>" class="d-block mb-4 h-100">
                        <img class="img-fluid img-card" src="<?= $anime->img ?>" alt="">
                        <div class="middle-card">
                            <img class="btn-play" src="<?= $this->basePath('img/Anime/icons/play-anime.png')?>">
                        </div>
                    </a>
                </li>
            <?php endforeach ?>
        </ul>
    </div>
</div>

