<div id="wrapper">

    <span id="controlL" class="left-controls" role="button" aria-label="See Previous Modules">
        <b class="fa fa-chevron-left fa-chevron-left-extra" aria-hidden="true"></b>
    </span>

    <h3 class="my-4">Continuar Assistindo</h3>

    <div class="title text-center h1">Module Selection Area</div>

    <div class="module-section clearfix">
        <!-- <button class="btn arrow-guides fa-chevron-left"></button> -->
        <ul id="content">

            <li class="card effect1">
                <div class="inside-top">
                    <img src="http://placehold.it/350x150">
                </div>
            </li>
            <li class="card">
                <div class="inside-top">
                    <img src="http://placehold.it/350x150">
                </div>
            </li>
            <li class="card">
                <div class="inside-top">
                    <img src="http://placehold.it/350x150">
                </div>
            </li>
            <li class="card">
                <div class="inside-top">
                    <img src="http://placehold.it/350x150">
                </div>
            </li>
            <li class="card">
                <div class="inside-top">
                    <img src="http://placehold.it/350x150">
                </div>
            </li>
            <li class="card">
                <div class="inside-top">
                    <img src="http://placehold.it/350x150">
                </div>
            </li>
            <li class="card">
                <div class="inside-top">
                    <img src="http://placehold.it/350x150">
                </div>
            </li>
            <li class="card">
                <div class="inside-top">
                    <img src="http://placehold.it/350x150">
                </div>
            </li>
            <li class="card">
                <div class="inside-top">
                    <img src="http://placehold.it/350x150">
                </div>
            </li>
            <li class="card">
                <div class="inside-top">
                    <img src="http://placehold.it/350x150">
                </div>
            </li>
            <li class="card">
                <div class="inside-top">
                    <img src="http://placehold.it/350x150">
                </div>
            </li>
            <li class="card">
                <div class="inside-top">
                    <img src="http://placehold.it/350x150">
                </div>
            </li>
            <li class="card">
                <div class="inside-top">
                    <img src="http://placehold.it/350x150">
                </div>
            </li>
            <li class="card">
                <div class="inside-top">
                    <img src="http://placehold.it/350x150">
                </div>
            </li>
            <li class="card">
                <div class="inside-top">
                    <img src="http://placehold.it/350x150">
                </div>
            </li>
            <li class="card">
                <div class="inside-top">
                    <img src="http://placehold.it/350x150">
                </div>
            </li>
            <li class="card">
                <div class="inside-top">
                    <img src="http://placehold.it/350x150">
                </div>
            </li>
            <li class="card">
                <div class="inside-top">
                    <img src="http://placehold.it/350x150">
                </div>
            </li>
            <li class="card">
                <div class="inside-top">
                    <img src="http://placehold.it/350x150">
                </div>
            </li>
            <li class="card">
                <div class="inside-top">
                    <img src="http://placehold.it/350x150">
                </div>
            </li>
            <li class="card">
                <div class="inside-top">
                    <img src="http://placehold.it/350x150">
                </div>
            </li>
            <li class="card">
                <div class="inside-top">
                    <img src="http://placehold.it/350x150">
                </div>
            </li>
            <li class="card">
                <div class="inside-top">
                    <img src="http://placehold.it/350x150">
                </div>

            </li>

        </ul>



    </div><!--end of module-section-->

    <span id="controlR" class="right-controls" role="button" aria-label="See Previous Modules">
    <b class="fa fa-chevron-right fa-chevron-right-extra" aria-hidden="true"></b>
  </span>
    <!-- <button class="btn arrow-guides-right fa-chevron-right"></button> -->



</div>
<script>
    $('#controlR').click(function() {
        event.preventDefault();
        $('#content').animate({
            marginLeft: "-=400px"
        }, "fast");
    });

    $('#controlL').click(function() {
        event.preventDefault();
        $('#content').animate({
            marginLeft: "+=400px"
        }, "fast");
    });

</script>