
<div class = "container">
    <div class="wrapper">
        <form action="/admin/login" method="post" name="Login_Form" class="form-signin">
            <h3 class="form-signin-heading">Welcome Back! Please Sign In</h3>
            <hr class="colorgraph"><br>

            <input type="text" autocomplete="username" class="form-control" name="Username" placeholder="Username" required="" autofocus="" />
            <input type="password" autocomplete="current-password" class="form-control" name="Password" placeholder="Password" required=""/>

            <button class="btn btn-lg btn-primary btn-block"  name="Submit" value="Login" type="Submit">Login</button>
        </form>
    </div>
</div>


<link rel="stylesheet" type="text/css" href="<?= $this->basePath('css/login.css') ?>">