<div class="img-wall-anime"></div>
<?php include('login.phtml') ?>

<div class="container-fluid">
    <?php include('navbar.phtml') ?>
    <?php include('carousel.phtml') ?>
</div>
<?php include('menu-top.phtml') ?>
<?php include('menu-left.phtml') ?>
<div class="container-search"></div>

<div id="loader-wrapper">
    <div id="loader"></div>
    <div class="loader-section section-left"></div>
    <div class="loader-section section-right"></div>
</div>

<?php include('login.phtml') ?>

<link rel="stylesheet" type="text/css" href="<?= $this->basePath('css/index.css') ?>">
<link rel="stylesheet" type="text/css" href="<?= $this->basePath('css/jquery-ui-base.css') ?>">
<script src="<?= $this->basePath('js/module/Application/Index/xhr/Anime.js') ?>"></script>
<script src="<?= $this->basePath('js/module/Application/Index/Helper.js') ?>"></script>

<script type="text/javascript">
    $(window).on('load', function() {
        (new App()).start();
    });
</script>

<noscript>Your browser does not support JavaScript!</noscript>


