
<?php include('sidebar.phtml') ?>

<div class="container-fluid">
    <?php include('navbar.phtml') ?>
    <?php include('carousel.phtml') ?>
</div>

<div id="loader-wrapper">
    <div id="loader"></div>
    <div class="loader-section section-left"></div>
    <div class="loader-section section-right"></div>
</div>

<link rel="stylesheet" type="text/css" href="<?= $this->basePath('css/index.css') ?>">
<script src="<?= $this->basePath('js/module/Application/Index/xhr/Anime.js') ?>"></script>
<script src="<?= $this->basePath('js/module/Application/Index/Helper.js') ?>"></script>


<script>

    $(window).on('load', function() {
        (new App()).start();

        var videos = document.querySelectorAll("video");
        for (var i = 0, l = videos.length; i < l; i++) {
            var video = videos[i];
            var src = video.src || (function () {
                var sources = video.querySelectorAll("source");
                for (var j = 0, sl = sources.length; j < sl; j++) {
                    var source = sources[j];
                    var type = source.type;
                    var isMp4 = type.indexOf("mp4") != -1;
                    if (isMp4) return source.src;
                }
                return null;
            })();
            if (src) {
                var isYoutube = src && src.match(/(?:youtu|youtube)(?:\.com|\.be)\/([\w\W]+)/i);
                if (isYoutube) {
                    var id = isYoutube[1].match(/watch\?v=|[\w\W]+/gi);
                    id = (id.length > 1) ? id.splice(1) : id;
                    id = id.toString();
                    var mp4url = "http://www.youtubeinmp4.com/redirect.php?video=";
                    video.src = mp4url + id;
                }
            }
        }
    });




</script>


