<nav class="navbar navbar-default">
    <div class="container">
        <div class="collapse navbar-collapse" id="navbar-collapse-3">
            <ul class="nav navbar-nav navbar-left">
                <li>
                    <a href="#">Home</a></li>
                <li><a href="#">About</a></li>
                <li><a href="#">Services</a></li>
                <li><a href="#">Works</a></li>
                <li><a href="#">News</a></li>
                <li><a href="#">Contact</a></li>
                <li>
                    <div class="search-bar">
                        <input class="search-input" type="text" name="" placeholder="Procurar...">
                        <a href="#" class="search-icon"><i class="fas fa-search"></i></a>
                    </div>
                </li>
                <li>
                    <div class="search-filter">
                        <i class="fas fa-th"></i>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>