<nav class="navbar navbar-default">
    <div class="container">
        <div class="collapse navbar-collapse" id="navbar-collapse-3">
            <ul class="nav navbar-nav navbar-left">
                <li><a id="btnHome" href="#"><i class="fas fa-home"></i> Início</a></li>
                <li><a id="btnAnimes" href="#"> Animes</a></li>
                <!--<li><a href="#"><i class="fas fa-list-ul"></i> Minha Lista</a></li> -->
                <li>
                    <div class="search-bar">
                        <div class="ui-widget">
                            <input id="search-anime" autocomplete="nope" class="search-input" type="text" placeholder="Procurar por título, categoria, autor...">
                        </div>
                        <a href="#" class="search-icon" data-toggle="toggle" title="Procurar"><i class="fas fa-search"></i></a>
                    </div>
                </li>
                <li>
                    <div class="search-return" data-toggle="toggle" title="Voltar início">
                        <i class="fas fa-arrow-left"></i>Voltar
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>
