
<div id="wrapper" class="toggled">
    <nav class="navbar navbar-inverse navbar-fixed-top" id="sidebar-wrapper" role="navigation">
        <ul class="nav sidebar-nav">
           <!--
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Works <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                    <li class="dropdown-header">Dropdown heading</li>
                    <li><a href="#">Action</a></li>
                    <li><a href="#">Another action</a></li>
                    <li><a href="#">Something else here</a></li>
                    <li><a href="#">Separated link</a></li>
                    <li><a href="#">One more separated link</a></li>
                </ul>
            </li>-->
        </ul>
    </nav>
    <div id="page-content-wrapper">
        <div class="container">
            <div class="row">
                <!--<h4> Resultados: </h4> -->
                <ul class="container-search"></ul>
            </div>
        </div>
    </div>
</div>